apiVersion: extensions.kubesphere.io/v1alpha1
kind: APIService
metadata:
  name: v1alpha1.demo.kubesphere.io
  annotations:
    meta.helm.sh/release-name: demo-0.10.0
spec:
  group: demo.kubesphere.io                               # API Group
  version: v1alpha1                                         # API Version
  endpoint: http://{{ include "backend.fullname" . }}.{{ .Release.Namespace }}.svc  # backend
#  insecureSkipTLSVerify: true
status:
  enabled: true
